### ISSUE TITLE
Object not found

### ISSUE THREAD

**Issue by hyhpm4n** [lloricode/ci-capstone#75]
I have imported the database in XAMPP (phpmyadmin), put the files in htdocs. i changed the name folder into "enrollment" run localhost/enrollment.  below is the problem, please help. sorry for my bad english.
![untitled](https://cloud.githubusercontent.com/assets/21338058/26788862/272695da-4a41-11e7-8209-adc329b8e75e.png)

**Comment by lloricode** [comment]
@githubwasabi 
,  hmm try to rename the folder as the name of repo `ci-capstone`,
because it was already configured in `$config['base_url'] = 'http://[::1]/ci-capstone/';` in `application/config/development/config.php` `line 29`

[here the link of config](https://github.com/lloricode/ci-capstone/blob/developing/application/config/development/config.php#L29)

that why it will redirect in url `http://[::1]/ci-capstone/en/auth/login`

**Comment by lloricode** [comment]
or if you want, just modify a **config** `base_url` with the new folder name you want :)

**Comment by hyhpm4n** [comment]
Thank you sir.  It worked :D life saver :D
