### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by cc-supremacy** [lloricode/ci-capstone#83]
![qweqweqwe](https://github.com/lloricode/ci-capstone/assets/130909804/85f2bb9e-2970-4b6b-b6e5-5c5eaa57fa26)

**Comment by lloricode** [comment]
can you give me more details? also plan to archive this, because I'm not active in codeigniter anymore,

**Comment by cc-supremacy** [comment]
> can you give me more details? also plan to archive this, because I'm not active in codeigniter anymore,

i did the readme stuff and tried to open it but it just shows me that. is it a codeigniter version issue?

**Comment by lloricode** [comment]
I'm not sure about it. As I mentioned, it has been 6 years since I moved to Laravel. It's possible that you are using the latest PHP version. I recommend using PHP <= 7.0 to ensure that this works. Unfortunately, I don't have the time to fix it to make it compatible with the current latest PHP version (8.2).
